JFLAGS = -g
JC = javac
OPT = -O3
#OPT = -g
WARN = -Wall


InsertionSort: InsertionSort.class
	java InsertionSort

InsertionSort.class: InsertionSort.java
	$(JC) $(JFLAGS) InsertionSort.java

clean:
	$(RM) InsertionSort.class

clobber:
	$(RM) InsertionSort.class


